### ISSUE TITLE
Ability to create more than one instance of EventBus

### ISSUE THREAD

**Issue by voter101** [arkency/event-bus#1]
Currently when importing event bus, the moduling mechanism returns the one and the same instance of EventBus. That's not what we always want to do, so there should be a way to create more another instance of event-bus.

The export is evaluated once per runtime. That's how we want to ensure, we got "global" eventing bus without actually using any globals or singletons.

**Comment by Killavus** [comment]
Implemented in https://github.com/arkency/event-bus/commit/f91bbed4c77947ab4d9c5604b1ba3f5dc4a88621 with tests.
