### ISSUE TITLE
How is this package different from node's native EventEmitter package?

### ISSUE THREAD

**Issue by hbarcelos** [arkency/event-bus#4]
Why would one choose to use this module instead of [EventEmitter](https://nodejs.org/api/events.html)?

**Comment by paneq** [comment]
> How is this package different from node's native EventEmitter package?

I don't know. We used it in browsers, not in node.js

> Why would one choose to use this module instead of EventEmitter?

I don't know. Perhaps 10 times smaller API surface is valuable? It was useful to us 2 years ago. In the meantime the ecosystem could have changed.

**Comment by hbarcelos** [comment]
I see, thank's for the clarification.
I'm starting a new application and I'm gathering some modules to use.

I'm currently looking for an event module that supports pattern matching in subcription (since `event-emitter` doesn't). I couldn't find anything related to this in the README, so I decided to ask.

Thank you (:
