### ISSUE TITLE
eventing-bus/lib/window_event_stream removed

### ISSUE THREAD

**Issue by orlandodemauro** [arkency/event-bus#5]
hi all,

is there any reason why the window_event_stream has been removed in commit cbcebe2c55d4c951ee54682379e0707098ebc08f?

thank you

**Comment by lukedesu** [comment]
same issue here

```
ERROR in ./src/js/react/components/navigation/App.js
Module not found: Error: Can't resolve 'eventing-bus/lib/window_event_stream' in ...
```
for now I just use version 1.2.0 since it is okay for me.

**Comment by voter101** [comment]
Hey. With version 2.0.0, I decided to abandon the support for the window event stream. You can easily add the support of that in your own code. Look into #6 for an example how.
